Df user fields
flow123d/flow123d pull request #1456
Opened 2022-06-17 07:20 UTC by dflanderka

Solves #1450

2022-06-27 07:41 UTC, jbrezmorf commented on src/fields/field_set.hh
>       */
Describe meaning of  default field set.

2022-06-27 07:45 UTC, jbrezmorf commented on src/mechanics/elasticity.cc
> +       	eq_fields_->init_user_fields(user_fields_arr, time_->step());
How to deal with the time step?

2022-06-27 07:49 UTC, jbrezmorf commented on src/mechanics/elasticity.cc
> +       	eq_fields_->init_user_fields(user_fields_arr, time_->step());
It seems that we have tests for reading the user fields in different equations. We should also test output of the user fields and test user fields of different shape. This common test would rather be in 03_output

2022-09-05 09:10 UTC, jbrezmorf requested changes

2022-09-05 09:10 UTC, jbrezmorf commented on src/flow/darcy_flow_lmh.cc
> +        .declare_key("user_fields", it::Array(DarcyLMH::EqFields().make_user_field_type(equation_name())),
Move key definition into EquationBase.
Create there a method for processing this key and calling init_user_fields.

2022-09-07 15:53 UTC, dflanderka commented on src/flow/darcy_flow_mh_output.cc
>  	output_fields += darcy_flow->eq_fieldset();
Will be solved in #1483

2022-09-07 15:59 UTC, dflanderka commented on src/fields/field_set.cc
> +        .declare_key("scalar_field", scalar_field.get_input_type(),
Will be solved in #1484

2022-10-03 15:01 UTC, merged